#!/usr/bin/env python3
"""
Expand state coverage: Ashtavinayak, modern temples (Delhi Akshardham/ISKCON),
and more popular state/local shrines beyond the classic circuits.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
TEMPLES = DATA / "temples"
sys.path.insert(0, str(ROOT / "scripts"))
from sync_groups import base_detail, dump_json, load_json  # type: ignore

PORTALS = load_json(DATA / "state-portals.json")

NEW = [
    # —— Maharashtra: Ashtavinayak (traditional Morgaon-start order) ——
    {
        "slug": "moreshwar-morgaon",
        "name": "Moreshwar Temple, Morgaon",
        "deity": "Lord Ganesha (Moreshwar)",
        "location": "Morgaon, Pune district, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "glyph": "मो",
        "famousFor": "First Ashtavinayak — peacock-form Ganesha",
        "summary": "Morgaon’s Moreshwar is traditionally the starting point of the Maharashtra Ashtavinayak yatra.",
        "mythology": "Moreshwar is worshipped as Ganesha who vanquished the demon Sindhu with a peacock (mora) mount. Morgaon is the classic first stop of the eight-temple Ashtavinayak circuit around Pune.",
        "scriptureLinks": ["Ganesha Purana / Mudgala Purana traditions", "Ashtavinayak yatra lore"],
        "lat": 18.2756,
        "lng": 74.3236,
        "mapQuery": "Moreshwar Temple Morgaon",
        "nearestRail": "Daund / Pune",
        "nearestAirport": "Pune",
        "officialWebsite": "https://www.maharashtratourism.gov.in/",
        "festivals": ["Ganesh Chaturthi", "Maghi Chaturthi"],
        "packages": ["Ashtavinayak 2–3 day circuit from Pune", "Morgaon day darshan"],
    },
    {
        "slug": "siddhivinayak-siddhatek",
        "name": "Siddhivinayak Temple, Siddhatek",
        "deity": "Lord Ganesha (Siddhivinayak)",
        "location": "Siddhatek, Ahmednagar district, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "glyph": "सि",
        "famousFor": "Ashtavinayak — right-trunk Siddhi Vinayaka",
        "summary": "Siddhatek’s riverside Siddhivinayak is the second temple of the Ashtavinayak yatra.",
        "mythology": "Tradition holds that Vishnu received siddhi (spiritual power) after worshipping Ganesha here before battling the demons Madhu and Kaitabha. The right-turned trunk form is especially revered.",
        "lat": 18.3440,
        "lng": 74.7180,
        "mapQuery": "Siddhivinayak Temple Siddhatek",
        "nearestRail": "Daund",
        "nearestAirport": "Pune",
        "officialWebsite": "https://www.maharashtratourism.gov.in/",
    },
    {
        "slug": "ballaleshwar-pali",
        "name": "Ballaleshwar Temple, Pali",
        "deity": "Lord Ganesha (Ballaleshwar)",
        "location": "Pali, Raigad district, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "glyph": "ब",
        "famousFor": "Ashtavinayak — named for devotee Ballal",
        "summary": "Pali’s Ballaleshwar commemorates the child-devotee Ballal and is a core Ashtavinayak seat.",
        "mythology": "Local lore tells of Ballal, a boy whose devotion to Ganesha was tested by villagers and then blessed when the Lord appeared. The temple retains that child-bhakti story at its heart.",
        "lat": 18.5410,
        "lng": 73.2200,
        "mapQuery": "Ballaleshwar Temple Pali",
        "nearestRail": "Karjat / Pune",
        "nearestAirport": "Pune / Mumbai",
        "officialWebsite": "https://www.maharashtratourism.gov.in/",
    },
    {
        "slug": "varadavinayak-mahad",
        "name": "Varadavinayak Temple, Mahad",
        "deity": "Lord Ganesha (Varadavinayak)",
        "location": "Mahad, Raigad district, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "glyph": "व",
        "famousFor": "Ashtavinayak — boon-giving Vinayaka",
        "summary": "Mahad’s Varadavinayak is the boon-granting Ashtavinayak shrine of the Konkan–Pune belt.",
        "mythology": "Varadavinayak is praised as the giver of varada (boons). A continuously burning lamp tradition and forested setting shape the pilgrim experience.",
        "lat": 18.5570,
        "lng": 73.4220,
        "mapQuery": "Varadavinayak Temple Mahad Raigad",
        "nearestRail": "Karjat / Khopoli",
        "nearestAirport": "Pune / Mumbai",
        "officialWebsite": "https://www.maharashtratourism.gov.in/",
    },
    {
        "slug": "chintamani-theur",
        "name": "Chintamani Temple, Theur",
        "deity": "Lord Ganesha (Chintamani)",
        "location": "Theur, Pune district, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "glyph": "चि",
        "famousFor": "Ashtavinayak — wish-fulfilling Chintamani",
        "summary": "Theur’s Chintamani is among the most visited Ashtavinayak temples near Pune.",
        "mythology": "Named for the wish-fulfilling gem Chintamani, the shrine is linked to Kapila and other sage traditions. Closest major Ashtavinayak stop to Pune city for many day pilgrims.",
        "lat": 18.5250,
        "lng": 74.0460,
        "mapQuery": "Chintamani Temple Theur",
        "nearestRail": "Pune",
        "nearestAirport": "Pune",
        "officialWebsite": "https://www.maharashtratourism.gov.in/",
    },
    {
        "slug": "girijatmaj-lenyadri",
        "name": "Girijatmaj Temple, Lenyadri",
        "deity": "Lord Ganesha (Girijatmaj)",
        "location": "Lenyadri, Pune district, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "glyph": "गि",
        "famousFor": "Ashtavinayak — cave temple of Parvati’s son",
        "summary": "Lenyadri’s Girijatmaj is the cave Ashtavinayak — Ganesha as the son of Girija (Parvati).",
        "mythology": "Set in Buddhist-era caves later sanctified for Ganesha, Girijatmaj is worshipped as the child of Parvati. The hill climb is part of the vow for many devotees.",
        "lat": 19.1910,
        "lng": 73.8730,
        "mapQuery": "Girijatmaj Temple Lenyadri",
        "nearestRail": "Pune / Junnar region",
        "nearestAirport": "Pune",
        "officialWebsite": "https://www.maharashtratourism.gov.in/",
    },
    {
        "slug": "vighnahar-ozar",
        "name": "Vighnahar Temple, Ozar",
        "deity": "Lord Ganesha (Vighneshwar / Vighnahar)",
        "location": "Ozar, Pune district, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "glyph": "वि",
        "famousFor": "Ashtavinayak — remover of obstacles",
        "summary": "Ozar’s Vighnahar is the obstacle-removing Ganesha of the Ashtavinayak set.",
        "mythology": "Vighnahar (Vighneshwar) is praised for destroying the demon Vighnasura. Golden dome and riverine setting make Ozar a photogenic yatra stop.",
        "lat": 19.1880,
        "lng": 73.9580,
        "mapQuery": "Vighnahar Temple Ozar",
        "nearestRail": "Pune",
        "nearestAirport": "Pune",
        "officialWebsite": "https://www.maharashtratourism.gov.in/",
    },
    {
        "slug": "mahaganapati-ranjangaon",
        "name": "Mahaganapati Temple, Ranjangaon",
        "deity": "Lord Ganesha (Mahaganapati)",
        "location": "Ranjangaon, Pune district, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "glyph": "म",
        "famousFor": "Ashtavinayak — powerful Mahaganapati form",
        "summary": "Ranjangaon’s Mahaganapati often closes the Ashtavinayak circuit for Pune-based pilgrims.",
        "mythology": "Mahaganapati is linked to Shiva’s worship of Ganesha before the Tripurasura battle in regional telling. A powerful, regal form closes many Ashtavinayak itineraries.",
        "lat": 18.5610,
        "lng": 74.2450,
        "mapQuery": "Mahaganapati Temple Ranjangaon",
        "nearestRail": "Pune",
        "nearestAirport": "Pune",
        "officialWebsite": "https://www.maharashtratourism.gov.in/",
    },
    # —— Maharashtra popular ——
    {
        "slug": "siddhivinayak-mumbai",
        "name": "Siddhivinayak Temple, Mumbai",
        "deity": "Lord Ganesha (Siddhivinayak)",
        "location": "Prabhadevi, Mumbai, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "glyph": "सि",
        "famousFor": "Mumbai’s most famous Ganesha temple",
        "summary": "Prabhadevi Siddhivinayak — Maharashtra’s busiest urban Ganesha shrine.",
        "mythology": "A living centre of Mumbai devotion where film stars and ordinary families alike offer Tuesday vows. Distinct from Siddhatek’s Ashtavinayak Siddhivinayak.",
        "lat": 19.0170,
        "lng": 72.8300,
        "mapQuery": "Siddhivinayak Temple Mumbai",
        "nearestRail": "Dadar / Prabhadevi",
        "nearestAirport": "Mumbai",
        "officialWebsite": "https://www.siddhivinayak.org/",
        "festivals": ["Angaraki Chaturthi", "Ganesh Chaturthi"],
    },
    {
        "slug": "shirdi-sai",
        "name": "Shri Sai Baba Temple, Shirdi",
        "deity": "Shirdi Sai Baba",
        "location": "Shirdi, Ahmednagar district, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "glyph": "सा",
        "famousFor": "One of India’s largest modern pilgrimages",
        "summary": "Shirdi Sai Baba samadhi mandir — a defining Maharashtra and pan-India faith destination.",
        "mythology": "Sai Baba of Shirdi is revered across communities for teaching ‘Sabka Malik Ek’. The samadhi temple and dwarkamai mosque-form spaces structure a unique shared sacred landscape.",
        "lat": 19.7667,
        "lng": 74.4762,
        "mapQuery": "Shirdi Sai Baba Temple",
        "nearestRail": "Sainagar Shirdi",
        "nearestAirport": "Shirdi / Aurangabad / Pune",
        "officialWebsite": "https://www.sai.org.in/",
        "tags_extra": ["modern-temples"],
        "festivals": ["Ram Navami", "Guru Purnima", "Vijayadashami"],
    },
    {
        "slug": "mahalaxmi-kolhapur",
        "name": "Mahalaxmi Temple, Kolhapur",
        "deity": "Goddess Mahalaxmi (Ambabai)",
        "location": "Kolhapur, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "glyph": "ल",
        "famousFor": "Ambabai — Maharashtra’s great Lakshmi shrine",
        "summary": "Kolhapur Mahalaxmi (Ambabai) is among Maharashtra’s foremost Devi temples.",
        "mythology": "Ambabai of Karvir is worshipped as Mahalakshmi with strong Shakta and royal Maratha associations. Kirnotsav (sun-ray festivals) are locally celebrated.",
        "lat": 16.7050,
        "lng": 74.2433,
        "mapQuery": "Mahalaxmi Temple Kolhapur",
        "nearestRail": "Kolhapur",
        "nearestAirport": "Kolhapur / Belagavi / Pune",
        "officialWebsite": "https://www.mahalaxmikolhapur.com/",
        "festivals": ["Navaratri", "Kirnotsav"],
    },
    {
        "slug": "jejuri-khandoba",
        "name": "Khandoba Temple, Jejuri",
        "deity": "Lord Khandoba (Martanda Bhairava)",
        "location": "Jejuri, Pune district, Maharashtra",
        "state": "Maharashtra",
        "country": "India",
        "glyph": "खं",
        "famousFor": "Turmeric-smeared hill temple of Khandoba",
        "summary": "Jejuri’s Khandoba temple is a vibrant folk-Shaiva pilgrimage of Maharashtra.",
        "mythology": "Khandoba is worshipped as a form of Bhairava / Martanda — guardian deity of many Marathi families. Yellow turmeric (bhandara) offerings colour the entire hill.",
        "lat": 18.2760,
        "lng": 74.1590,
        "mapQuery": "Khandoba Temple Jejuri",
        "nearestRail": "Jejuri / Pune",
        "nearestAirport": "Pune",
        "officialWebsite": "https://www.maharashtratourism.gov.in/",
    },
    # —— Delhi: modern ——
    {
        "slug": "akshardham-delhi",
        "name": "Swaminarayan Akshardham, Delhi",
        "deity": "Bhagwan Swaminarayan & Akshar Purushottam devotion",
        "location": "Noida Mor, New Delhi, Delhi",
        "state": "Delhi",
        "country": "India",
        "glyph": "अ",
        "famousFor": "Monumental modern Hindu complex on the Yamuna",
        "summary": "Delhi Akshardham — a vast contemporary Swaminarayan complex of stone, exhibitions, and evening water-show devotion.",
        "mythology": "Built by BAPS, Akshardham presents Swaminarayan theology through architecture, mandir, and cultural exhibitions. It is a modern pilgrimage landmark rather than an ancient sthala — yet it shapes how millions encounter living Hindu devotion in the capital.",
        "scriptureLinks": ["Swaminarayan / BAPS tradition", "Contemporary Hindu sacred architecture"],
        "lat": 28.6127,
        "lng": 77.2773,
        "mapQuery": "Akshardham Temple Delhi",
        "nearestRail": "Akshardham Metro / New Delhi",
        "nearestAirport": "Delhi (DEL)",
        "officialWebsite": "https://akshardham.com/",
        "tags_extra": ["modern-temples"],
        "dressCode": "Modest clothing required; follow BAPS entry and security rules.",
        "restrictions": "Cameras/bags rules are strict — check official visitor guidelines.",
        "festivals": ["Diwali / Annakut", "Swaminarayan Jayanti observances"],
        "bestTime": "October–March evenings for the complex and water show (ticketed segments).",
    },
    {
        "slug": "iskcon-delhi",
        "name": "ISKCON Temple, Delhi",
        "deity": "Radha–Krishna (ISKCON)",
        "location": "Hare Krishna Hill, East of Kailash, New Delhi",
        "state": "Delhi",
        "country": "India",
        "glyph": "इ",
        "famousFor": "Capital’s major ISKCON Krishna temple",
        "summary": "ISKCON Delhi — a modern Gaudiya Vaishnava centre with temple, museum, and prasadam culture.",
        "mythology": "Part of the global ISKCON movement founded by A. C. Bhaktivedanta Swami Prabhupada, the Delhi temple spreads congregational chanting of the Hare Krishna mantra and Bhagavata devotion in an urban campus setting.",
        "scriptureLinks": ["Bhagavata Purana", "Gaudiya Vaishnava / ISKCON tradition"],
        "lat": 28.5535,
        "lng": 77.2490,
        "mapQuery": "ISKCON Temple East of Kailash Delhi",
        "nearestRail": "Kailash Colony / Nehru Place Metro",
        "nearestAirport": "Delhi (DEL)",
        "officialWebsite": "https://iskcondelhi.com/",
        "tags_extra": ["modern-temples"],
        "festivals": ["Janmashtami", "Radhashtami", "Gaura Purnima"],
    },
    {
        "slug": "chhatarpur-temple-delhi",
        "name": "Chhatarpur Temple, Delhi",
        "deity": "Goddess Katyayani / multiple shrines",
        "location": "Chhatarpur, New Delhi, Delhi",
        "state": "Delhi",
        "country": "India",
        "glyph": "छ",
        "famousFor": "Vast modern temple campus in South Delhi",
        "summary": "Chhatarpur Mandir — one of Delhi’s largest temple complexes, centred on Goddess Katyayani.",
        "mythology": "A late-20th-century complex that grew into a multi-shrine campus. Navaratri draws enormous NCR crowds. Represents modern urban temple patronage on a grand scale.",
        "lat": 28.5020,
        "lng": 77.1750,
        "mapQuery": "Chhatarpur Temple Delhi",
        "nearestRail": "Chhatarpur Metro",
        "nearestAirport": "Delhi (DEL)",
        "officialWebsite": "https://delhitourism.gov.in/",
        "tags_extra": ["modern-temples"],
        "festivals": ["Navaratri", "Diwali"],
    },
    {
        "slug": "birla-mandir-delhi",
        "name": "Laxminarayan Temple (Birla Mandir), Delhi",
        "deity": "Lakshmi–Narayan",
        "location": "Mandir Marg, New Delhi, Delhi",
        "state": "Delhi",
        "country": "India",
        "glyph": "बि",
        "famousFor": "Historic Birla temple of New Delhi",
        "summary": "Delhi’s Laxminarayan (Birla) Mandir — an early modern capital landmark temple.",
        "mythology": "Inaugurated in 1939 with Mahatma Gandhi’s association in popular memory, the temple opened worship beyond caste restrictions of its time — a modern social-sacred milestone as much as a Vaishnava shrine.",
        "lat": 28.6325,
        "lng": 77.1990,
        "mapQuery": "Birla Mandir Delhi",
        "nearestRail": "R.K. Ashram Marg / New Delhi",
        "nearestAirport": "Delhi (DEL)",
        "officialWebsite": "https://delhitourism.gov.in/",
        "tags_extra": ["modern-temples"],
    },
    # —— Uttar Pradesh ——
    {
        "slug": "ayodhya-ram-mandir",
        "name": "Ram Mandir, Ayodhya",
        "deity": "Lord Rama (Ramlala)",
        "location": "Ayodhya, Uttar Pradesh",
        "state": "Uttar Pradesh",
        "country": "India",
        "glyph": "रा",
        "famousFor": "Newly consecrated Ram Janmabhoomi temple",
        "summary": "Ayodhya’s Ram Mandir — the defining contemporary Ramayana-geography pilgrimage of North India.",
        "mythology": "Ayodhya is Rama’s legendary birthplace in the Ramayana. The present temple, consecrated in 2024, continues that epic geography as a living national pilgrimage. Local and pan-Indian devotion meet on the Sarayu’s banks.",
        "scriptureLinks": ["Valmiki Ramayana", "Ramcharitmanas", "Ayodhya mahatmya traditions"],
        "lat": 26.7956,
        "lng": 82.2000,
        "mapQuery": "Ram Mandir Ayodhya",
        "nearestRail": "Ayodhya Cantt / Ayodhya Dham",
        "nearestAirport": "Ayodhya (AYJ) / Lucknow",
        "officialWebsite": "https://srjbtkshetra.org/",
        "tags_extra": ["ramayana-trail", "modern-temples"],
        "festivals": ["Ram Navami", "Diwali", "Sharad Purnima observances"],
        "bestTime": "October–March; peak festival crowds need advance planning.",
    },
    {
        "slug": "banke-bihari-vrindavan",
        "name": "Banke Bihari Temple, Vrindavan",
        "deity": "Lord Krishna (Banke Bihari)",
        "location": "Vrindavan, Mathura, Uttar Pradesh",
        "state": "Uttar Pradesh",
        "country": "India",
        "glyph": "बं",
        "famousFor": "Beloved Krishna temple of Vrindavan lanes",
        "summary": "Banke Bihari — among Vrindavan’s most loved Krishna shrines in the Braj pilgrimage.",
        "mythology": "Banke Bihari is worshipped in a tribhanga (three-bend) form associated with Swami Haridas traditions. Curtain rituals and dense Braj bhakti define the darshan style.",
        "lat": 27.5796,
        "lng": 77.7006,
        "mapQuery": "Banke Bihari Temple Vrindavan",
        "nearestRail": "Mathura Junction",
        "nearestAirport": "Agra / Delhi",
        "officialWebsite": "https://uptourism.gov.in/",
        "festivals": ["Janmashtami", "Radhashtami", "Holi of Braj"],
    },
    {
        "slug": "prem-mandir-vrindavan",
        "name": "Prem Mandir, Vrindavan",
        "deity": "Radha–Krishna (Jagadguru Kripalu Parishat)",
        "location": "Vrindavan, Mathura, Uttar Pradesh",
        "state": "Uttar Pradesh",
        "country": "India",
        "glyph": "प्रे",
        "famousFor": "Illuminated modern marble temple of Braj",
        "summary": "Prem Mandir — a contemporary Vrindavan landmark known for carved leela panels and evening lights.",
        "mythology": "A 21st-century temple presenting Krishna–Radha leelas in sculpted marble. Popular with first-time Braj visitors seeking an accessible modern sacred complex.",
        "lat": 27.5720,
        "lng": 77.6720,
        "mapQuery": "Prem Mandir Vrindavan",
        "nearestRail": "Mathura Junction",
        "nearestAirport": "Agra / Delhi",
        "officialWebsite": "https://jkp.org.in/",
        "tags_extra": ["modern-temples"],
    },
    {
        "slug": "sankat-mochan-varanasi",
        "name": "Sankat Mochan Hanuman Temple, Varanasi",
        "deity": "Lord Hanuman",
        "location": "Lanka, Varanasi, Uttar Pradesh",
        "state": "Uttar Pradesh",
        "country": "India",
        "glyph": "सं",
        "famousFor": "Varanasi’s famous Hanuman temple & music tradition",
        "summary": "Sankat Mochan — a key Hanuman shrine of Kashi, linked to Tulsidas tradition.",
        "mythology": "Associated with Goswami Tulsidas, who is said to have received Hanuman’s darshan here. Tuesday/Saturday crowds and the Sankat Mochan music festival keep living arts tied to devotion.",
        "lat": 25.2820,
        "lng": 83.0000,
        "mapQuery": "Sankat Mochan Temple Varanasi",
        "nearestRail": "Varanasi Junction",
        "nearestAirport": "Varanasi (VNS)",
        "officialWebsite": "https://uptourism.gov.in/",
        "tags_extra": ["ramayana-trail"],
    },
    # —— Gujarat ——
    {
        "slug": "akshardham-gandhinagar",
        "name": "Swaminarayan Akshardham, Gandhinagar",
        "deity": "Bhagwan Swaminarayan",
        "location": "Gandhinagar, Gujarat",
        "state": "Gujarat",
        "country": "India",
        "glyph": "अ",
        "famousFor": "BAPS Akshardham complex of Gujarat",
        "summary": "Gandhinagar Akshardham — Gujarat’s monumental Swaminarayan temple and exhibition campus.",
        "mythology": "The first great BAPS Akshardham complex, presenting Swaminarayan’s life and teachings through temple and museum spaces. A modern Gujarat pilgrimage icon.",
        "lat": 23.2340,
        "lng": 72.6750,
        "mapQuery": "Akshardham Temple Gandhinagar",
        "nearestRail": "Gandhinagar Capital / Ahmedabad",
        "nearestAirport": "Ahmedabad",
        "officialWebsite": "https://akshardham.com/gujarat/",
        "tags_extra": ["modern-temples"],
    },
    {
        "slug": "ambaji",
        "name": "Ambaji Temple",
        "deity": "Goddess Amba",
        "location": "Ambaji, Banaskantha, Gujarat",
        "state": "Gujarat",
        "country": "India",
        "glyph": "अं",
        "famousFor": "Major Shakti shrine of North Gujarat",
        "summary": "Ambaji — one of Gujarat’s foremost Devi pilgrimages at the Aravalli edge.",
        "mythology": "Amba Mata is worshipped as a powerful Shakti of Gujarat; the Gabbar hill and temple town form a classic western India Devi yatra.",
        "lat": 24.3310,
        "lng": 72.8510,
        "mapQuery": "Ambaji Temple Gujarat",
        "nearestRail": "Abu Road / Palanpur region",
        "nearestAirport": "Ahmedabad / Udaipur",
        "officialWebsite": "https://www.gujarattourism.com/",
        "festivals": ["Bhadarvi Purnima", "Navaratri"],
    },
    # —— Tamil Nadu ——
    {
        "slug": "meenakshi-madurai",
        "name": "Meenakshi Amman Temple, Madurai",
        "deity": "Goddess Meenakshi & Lord Sundareswarar",
        "location": "Madurai, Tamil Nadu",
        "state": "Tamil Nadu",
        "country": "India",
        "glyph": "मी",
        "famousFor": "Dravidian temple city icon of Tamil Nadu",
        "summary": "Madurai Meenakshi — among the world’s great living temple complexes.",
        "mythology": "Meenakshi (the fish-eyed goddess) and Sundareswarar (Shiva) are the divine couple of Madurai. The temple’s gopurams, halls, and Chithirai festival wedding reenactment define Tamil sacred urbanism.",
        "scriptureLinks": ["Tamil Shaiva–Shakta sthala purana", "Tevaram landscape"],
        "lat": 9.9195,
        "lng": 78.1193,
        "mapQuery": "Meenakshi Temple Madurai",
        "nearestRail": "Madurai Junction",
        "nearestAirport": "Madurai",
        "officialWebsite": "https://www.maduraimeenakshi.hrce.tn.gov.in/",
        "festivals": ["Chithirai Festival", "Navaratri", "Float Festival"],
        "dressCode": "Traditional dress preferred; follow HR&CE notices.",
    },
    {
        "slug": "kapaleeshwarar-chennai",
        "name": "Kapaleeshwarar Temple, Mylapore",
        "deity": "Lord Shiva (Kapaleeshwarar) & Goddess Karpagambal",
        "location": "Mylapore, Chennai, Tamil Nadu",
        "state": "Tamil Nadu",
        "country": "India",
        "glyph": "क",
        "famousFor": "Chennai’s classic Dravidian neighbourhood temple",
        "summary": "Kapaleeshwarar of Mylapore — Chennai’s signature Shaiva temple and tank festival.",
        "mythology": "Linked to the peacock (mayil) lore of Mylapore and Parvati’s penance. The temple tank and Panguni festival are city landmarks.",
        "lat": 13.0336,
        "lng": 80.2697,
        "mapQuery": "Kapaleeshwarar Temple Mylapore",
        "nearestRail": "Thirumayilai / Chennai",
        "nearestAirport": "Chennai",
        "officialWebsite": "https://hrce.tn.gov.in/hrcehome/",
        "festivals": ["Panguni Peruvizha", "Pradosham"],
    },
    # —— Karnataka ——
    {
        "slug": "udupi-krishna",
        "name": "Sri Krishna Temple, Udupi",
        "deity": "Lord Krishna (Udupi Sri Krishna)",
        "location": "Udupi, Karnataka",
        "state": "Karnataka",
        "country": "India",
        "glyph": "उ",
        "famousFor": "Kanakana kindi window darshan & Madhva tradition",
        "summary": "Udupi Sri Krishna Matha — coastal Karnataka’s great Vaishnava seat of Madhvacharya tradition.",
        "mythology": "Associated with Madhvacharya and the famous window darshan (Kanakana kindi) lore of devotee Kanakadasa. Paryaya system rotates worship among ashta mathas.",
        "lat": 13.3410,
        "lng": 74.7470,
        "mapQuery": "Udupi Krishna Temple",
        "nearestRail": "Udupi",
        "nearestAirport": "Mangaluru",
        "officialWebsite": "https://udipikrishnamutt.com/",
        "festivals": ["Paryaya", "Krishna Janmashtami", "Madhwa Navami"],
    },
    {
        "slug": "iskcon-bengaluru",
        "name": "ISKCON Temple, Bengaluru",
        "deity": "Radha–Krishna (ISKCON)",
        "location": "Rajajinagar / Chord Road, Bengaluru, Karnataka",
        "state": "Karnataka",
        "country": "India",
        "glyph": "इ",
        "famousFor": "Bengaluru’s landmark ISKCON hill temple",
        "summary": "ISKCON Bengaluru — a major South Indian modern Krishna temple and cultural campus.",
        "mythology": "A prominent ISKCON centre known for gopuram skyline, prasadam, and Janmashtami crowds — urban bhakti in India’s tech capital.",
        "lat": 12.9900,
        "lng": 77.5510,
        "mapQuery": "ISKCON Temple Bangalore",
        "nearestRail": "Bengaluru City / Yesvantpur",
        "nearestAirport": "Bengaluru (BLR)",
        "officialWebsite": "https://www.iskconbangalore.org/",
        "tags_extra": ["modern-temples"],
        "festivals": ["Janmashtami", "Vaikunta Ekadasi"],
    },
    # —— Kerala ——
    {
        "slug": "padmanabhaswamy-thiruvananthapuram",
        "name": "Padmanabhaswamy Temple, Thiruvananthapuram",
        "deity": "Lord Vishnu (Ananta Padmanabha)",
        "location": "Thiruvananthapuram, Kerala",
        "state": "Kerala",
        "country": "India",
        "glyph": "प",
        "famousFor": "Ananta-shayana Vishnu & Travancore royal temple",
        "summary": "Sree Padmanabhaswamy — Kerala’s foremost Vishnu temple in the capital city.",
        "mythology": "Padmanabha reclines on Ananta; Travancore kings ruled as Padmanabha-dasas (servants of the Lord). Strict dress codes and unique ritual order apply.",
        "lat": 8.4827,
        "lng": 76.9436,
        "mapQuery": "Padmanabhaswamy Temple Trivandrum",
        "nearestRail": "Thiruvananthapuram Central",
        "nearestAirport": "Thiruvananthapuram",
        "officialWebsite": "https://www.sreepadmanabhaswamytemple.org/",
        "dressCode": "Strict traditional Kerala dress code for entry.",
        "festivals": ["Alpashi / Painkuni festivals", "Navaratri"],
    },
    {
        "slug": "attukal-bhagavathy",
        "name": "Attukal Bhagavathy Temple",
        "deity": "Goddess Attukal Bhagavathy",
        "location": "Attukal, Thiruvananthapuram, Kerala",
        "state": "Kerala",
        "country": "India",
        "glyph": "अ",
        "famousFor": "Attukal Pongala — among the world’s largest women’s gatherings",
        "summary": "Attukal Bhagavathy — famous for the massive Pongala offering by women devotees.",
        "mythology": "The goddess is linked to Kannaki / Bhadrakali regional traditions. Pongala sees kilometres of hearths — a living Kerala Shakta spectacle.",
        "lat": 8.4700,
        "lng": 76.9550,
        "mapQuery": "Attukal Temple Trivandrum",
        "nearestRail": "Thiruvananthapuram Central",
        "nearestAirport": "Thiruvananthapuram",
        "officialWebsite": "https://www.attukal.org/",
        "festivals": ["Attukal Pongala"],
    },
    # —— West Bengal ——
    {
        "slug": "dakshineswar-kali",
        "name": "Dakshineswar Kali Temple",
        "deity": "Goddess Kali (Bhavatarini)",
        "location": "Dakshineswar, Kolkata, West Bengal",
        "state": "West Bengal",
        "country": "India",
        "glyph": "द",
        "famousFor": "Rani Rashmoni’s temple linked to Sri Ramakrishna",
        "summary": "Dakshineswar — riverside Kali temple central to modern Bengal’s spiritual history.",
        "mythology": "Founded by Rani Rashmoni in the 19th century and forever associated with Sri Ramakrishna Paramahamsa’s sadhana. A bridge between classical Kali worship and modern Hindu renewal.",
        "lat": 22.6550,
        "lng": 88.3575,
        "mapQuery": "Dakshineswar Kali Temple",
        "nearestRail": "Dakshineswar / Kolkata",
        "nearestAirport": "Kolkata",
        "officialWebsite": "https://wbtourism.gov.in/",
        "tags_extra": ["modern-temples"],
        "festivals": ["Kali Puja", "Snana Yatra days"],
    },
    {
        "slug": "belur-math",
        "name": "Belur Math",
        "deity": "Sri Ramakrishna / Universal temple ideal",
        "location": "Belur, Howrah, West Bengal",
        "state": "West Bengal",
        "country": "India",
        "glyph": "बे",
        "famousFor": "Headquarters of Ramakrishna Math & Mission",
        "summary": "Belur Math — Swami Vivekananda’s monastic seat and a modern universalist temple campus on the Hooghly.",
        "mythology": "Architecture deliberately weaves Hindu, Christian, and Islamic motifs to express Ramakrishna’s harmony of religions. A pilgrimage of modern Vedanta as much as ritual worship.",
        "lat": 22.6322,
        "lng": 88.3564,
        "mapQuery": "Belur Math",
        "nearestRail": "Belur Math / Howrah",
        "nearestAirport": "Kolkata",
        "officialWebsite": "https://belurmath.org/",
        "tags_extra": ["modern-temples"],
    },
    # —— Bihar / Punjab / Odisha / others ——
    {
        "slug": "vishnupad-gaya",
        "name": "Vishnupad Temple, Gaya",
        "deity": "Lord Vishnu (footprint shrine)",
        "location": "Gaya, Bihar",
        "state": "Bihar",
        "country": "India",
        "glyph": "वि",
        "famousFor": "Pinda-daan & Vishnu’s footprint tirtha",
        "summary": "Vishnupad Gaya — Bihar’s great ancestral-rite and Vishnu pilgrimage.",
        "mythology": "Tradition holds Vishnu’s footprint on the rock here. Gaya is central to pinda-daan rites for ancestors across North India.",
        "lat": 24.7914,
        "lng": 85.0002,
        "mapQuery": "Vishnupad Temple Gaya",
        "nearestRail": "Gaya Junction",
        "nearestAirport": "Gaya / Patna",
        "officialWebsite": "https://tourism.bihar.gov.in/",
        "festivals": ["Pitru Paksha period", "Vishnu-related observances"],
    },
    {
        "slug": "mahavir-mandir-patna",
        "name": "Mahavir Mandir, Patna",
        "deity": "Lord Hanuman",
        "location": "Patna Junction area, Patna, Bihar",
        "state": "Bihar",
        "country": "India",
        "glyph": "म",
        "famousFor": "Patna’s hugely popular Hanuman temple",
        "summary": "Mahavir Mandir Patna — one of Bihar’s busiest urban Hanuman shrines.",
        "mythology": "A modern trust-run temple known for massive Tuesday crowds and charitable work. Living Hanuman devotion in Bihar’s capital.",
        "lat": 25.6090,
        "lng": 85.1370,
        "mapQuery": "Mahavir Mandir Patna",
        "nearestRail": "Patna Junction",
        "nearestAirport": "Patna",
        "officialWebsite": "https://www.mahavirmandirpatna.org/",
        "tags_extra": ["modern-temples", "ramayana-trail"],
    },
    {
        "slug": "durgiana-amritsar",
        "name": "Durgiana Temple, Amritsar",
        "deity": "Goddess Durga / Lakshmi–Narayan complex",
        "location": "Amritsar, Punjab",
        "state": "Punjab",
        "country": "India",
        "glyph": "दु",
        "famousFor": "Amritsar’s major Hindu temple tank complex",
        "summary": "Durgiana Mandir — Amritsar’s prominent Devi–Vaishnava temple near the Golden Temple area.",
        "mythology": "A tank-and-temple complex associated with Durga worship and later Lakshmi–Narayan shrines. Often visited alongside Amritsar’s wider sacred geography.",
        "lat": 31.6330,
        "lng": 74.8650,
        "mapQuery": "Durgiana Temple Amritsar",
        "nearestRail": "Amritsar Junction",
        "nearestAirport": "Amritsar",
        "officialWebsite": "https://punjabtourism.punjab.gov.in/",
        "festivals": ["Navaratri", "Dussehra"],
    },
    {
        "slug": "lingaraj-bhubaneswar",
        "name": "Lingaraj Temple, Bhubaneswar",
        "deity": "Lord Shiva (Lingaraj / Harihara form traditions)",
        "location": "Bhubaneswar, Odisha",
        "state": "Odisha",
        "country": "India",
        "glyph": "लि",
        "famousFor": "Kalinga architecture icon of Odisha",
        "summary": "Lingaraj — Bhubaneswar’s great Shiva temple and old-town axis.",
        "mythology": "Lingaraj is the lord of Ekamra Kshetra (old Bhubaneswar). The temple synthesises Shaiva devotion with Odisha’s distinctive Kalinga temple form.",
        "lat": 20.2380,
        "lng": 85.8330,
        "mapQuery": "Lingaraj Temple Bhubaneswar",
        "nearestRail": "Bhubaneswar",
        "nearestAirport": "Bhubaneswar",
        "officialWebsite": "https://odishatourism.gov.in/",
        "festivals": ["Shivaratri", "Ashokashtami"],
        "restrictions": "Non-Hindu entry to inner temple may be restricted — follow notices.",
    },
    {
        "slug": "govind-dev-ji-jaipur",
        "name": "Govind Dev Ji Temple, Jaipur",
        "deity": "Lord Krishna (Govind Dev Ji)",
        "location": "City Palace complex, Jaipur, Rajasthan",
        "state": "Rajasthan",
        "country": "India",
        "glyph": "गो",
        "famousFor": "Jaipur’s royal Krishna temple",
        "summary": "Govind Dev Ji — the principal Krishna shrine of Jaipur’s old city.",
        "mythology": "The image is linked to Vrindavan traditions and Jaipur royal patronage. Evening aarti in the palace precinct is a classic Jaipur sacred experience.",
        "lat": 26.9260,
        "lng": 75.8240,
        "mapQuery": "Govind Dev Ji Temple Jaipur",
        "nearestRail": "Jaipur",
        "nearestAirport": "Jaipur",
        "officialWebsite": "https://devasthan.rajasthan.gov.in/",
        "festivals": ["Janmashtami", "Annkut"],
    },
    {
        "slug": "mansa-devi-panchkula",
        "name": "Mansa Devi Temple, Panchkula",
        "deity": "Goddess Mansa Devi",
        "location": "Panchkula / foothills near Chandigarh, Haryana",
        "state": "Haryana",
        "country": "India",
        "glyph": "मं",
        "famousFor": "Popular Shivalik foothills Devi yatra",
        "summary": "Mansa Devi of Panchkula — a major Haryana–Chandigarh region pilgrimage.",
        "mythology": "The goddess is believed to fulfil mannat (vows). Cable car and hill approach make it a family pilgrimage favourite of North India.",
        "lat": 30.6900,
        "lng": 76.8600,
        "mapQuery": "Mansa Devi Temple Panchkula",
        "nearestRail": "Chandigarh",
        "nearestAirport": "Chandigarh",
        "officialWebsite": "https://haryanatourism.gov.in/",
        "festivals": ["Navaratri"],
    },
    {
        "slug": "hadimba-manali",
        "name": "Hadimba Devi Temple, Manali",
        "deity": "Goddess Hadimba",
        "location": "Manali, Kullu, Himachal Pradesh",
        "state": "Himachal Pradesh",
        "country": "India",
        "glyph": "ह",
        "famousFor": "Cedar-forest pagoda temple of Manali",
        "summary": "Hadimba Devi — Manali’s iconic wooden temple in a cedar grove.",
        "mythology": "Linked to Hadimba of the Mahabharata (Bhima’s wife in the epic’s Himalayan episode). Local Kullu–Manali identity wraps epic memory in mountain wooden architecture.",
        "lat": 32.2470,
        "lng": 77.1870,
        "mapQuery": "Hadimba Devi Temple Manali",
        "nearestRail": "Joginder Nagar then road / Chandigarh road",
        "nearestAirport": "Bhuntar (Kullu)",
        "officialWebsite": "https://himachaltourism.gov.in/",
        "tags_extra": ["mahabharata-sites"],
        "festivals": ["Dhungri Mela"],
    },
    {
        "slug": "jakhoo-hanuman-shimla",
        "name": "Jakhoo Hanuman Temple, Shimla",
        "deity": "Lord Hanuman",
        "location": "Jakhoo Hill, Shimla, Himachal Pradesh",
        "state": "Himachal Pradesh",
        "country": "India",
        "glyph": "ज",
        "famousFor": "Giant Hanuman statue overlooking Shimla",
        "summary": "Jakhoo Temple — Shimla’s hilltop Hanuman shrine with a towering statue.",
        "mythology": "Local lore links the hill to Hanuman resting while searching for the Sanjeevani herb. The modern giant statue has made Jakhoo a Himachal photo-pilgrimage icon.",
        "lat": 31.1050,
        "lng": 77.1840,
        "mapQuery": "Jakhoo Temple Shimla",
        "nearestRail": "Shimla / Kalka",
        "nearestAirport": "Shimla (Jubbarhatti) / Chandigarh",
        "officialWebsite": "https://himachaltourism.gov.in/",
        "tags_extra": ["ramayana-trail", "modern-temples"],
    },
    {
        "slug": "danteshwari-dantewada",
        "name": "Danteshwari Temple, Dantewada",
        "deity": "Goddess Danteshwari",
        "location": "Dantewada, Chhattisgarh",
        "state": "Chhattisgarh",
        "country": "India",
        "glyph": "दं",
        "famousFor": "Kuladevi of Bastar & major Chhattisgarh Shakti seat",
        "summary": "Danteshwari of Dantewada — the spiritual heart of Bastar’s Devi tradition.",
        "mythology": "Often linked in local peetha memory to the tooth (danta) of Sati. The goddess is kuladevi of many Bastar communities; Dussehra of Bastar is her great public theology.",
        "lat": 18.9000,
        "lng": 81.3500,
        "mapQuery": "Danteshwari Temple Dantewada",
        "nearestRail": "Dantewada / Jagdalpur region",
        "nearestAirport": "Jagdalpur / Raipur",
        "officialWebsite": "https://www.tourism.cg.gov.in/",
        "festivals": ["Bastar Dussehra", "Navaratri"],
    },
    {
        "slug": "rajrappa-chhinnamastika",
        "name": "Chhinnamastika Temple, Rajrappa",
        "deity": "Goddess Chhinnamasta",
        "location": "Rajrappa, Ramgarh, Jharkhand",
        "state": "Jharkhand",
        "country": "India",
        "glyph": "छि",
        "famousFor": "River-confluence Chhinnamasta shrine",
        "summary": "Rajrappa — Jharkhand’s powerful Chhinnamasta temple at a river confluence.",
        "mythology": "Chhinnamasta is a fierce Mahavidya form. The confluence setting and regional Tantric–Shakta devotion make Rajrappa a distinctive eastern India pilgrimage.",
        "lat": 23.6320,
        "lng": 85.6750,
        "mapQuery": "Rajrappa Chhinnamasta Temple",
        "nearestRail": "Ramgarh / Ranchi region",
        "nearestAirport": "Ranchi",
        "officialWebsite": "https://tourism.jharkhand.gov.in/",
        "festivals": ["Makar Sankranti fair", "Navaratri"],
    },
    {
        "slug": "mangueshi-goa",
        "name": "Mangueshi Temple, Goa",
        "deity": "Lord Shiva (Manguesh)",
        "location": "Mangueshi, Ponda, Goa",
        "state": "Goa",
        "country": "India",
        "glyph": "मं",
        "famousFor": "Goa’s foremost Shiva temple",
        "summary": "Mangueshi — among Goa’s most important Hindu temples in the Ponda temple belt.",
        "mythology": "Manguesh is a form of Shiva central to Goan Saraswat tradition. Deepotsava lamps and distinctive Goan temple architecture define the experience.",
        "lat": 15.4450,
        "lng": 74.0040,
        "mapQuery": "Mangueshi Temple Goa",
        "nearestRail": "Karmali / Madgaon",
        "nearestAirport": "Goa (GOX / GOI)",
        "officialWebsite": "https://www.goatourism.gov.in/",
        "festivals": ["Magha Shivaratri", "Jatra / Deepotsava"],
    },
    {
        "slug": "shantadurga-goa",
        "name": "Shantadurga Temple, Kavlem",
        "deity": "Goddess Shantadurga",
        "location": "Kavlem, Ponda, Goa",
        "state": "Goa",
        "country": "India",
        "glyph": "शां",
        "famousFor": "Goa’s great peace-bringing Devi temple",
        "summary": "Shantadurga of Kavlem — a principal Goan Devi shrine near Mangueshi.",
        "mythology": "Shantadurga is worshipped as the goddess who brings shanti (peace) between Vishnu and Shiva in local lore — a uniquely Goan theological image.",
        "lat": 15.4120,
        "lng": 74.0150,
        "mapQuery": "Shantadurga Temple Kavlem",
        "nearestRail": "Karmali / Madgaon",
        "nearestAirport": "Goa",
        "officialWebsite": "https://www.goatourism.gov.in/",
        "festivals": ["Jatra", "Navaratri"],
    },
    {
        "slug": "kal-bhairav-ujjain",
        "name": "Kal Bhairav Temple, Ujjain",
        "deity": "Kal Bhairav",
        "location": "Ujjain, Madhya Pradesh",
        "state": "Madhya Pradesh",
        "country": "India",
        "glyph": "भै",
        "famousFor": "Liquor offering tradition & guardian of Ujjain",
        "summary": "Kal Bhairav of Ujjain — fierce guardian shrine often paired with Mahakaleshwar yatra.",
        "mythology": "Bhairava is Shiva’s fierce guardian form. Ujjain’s temple is famous for the unusual offering of liquor, accepted as the deity’s prasadam in local custom.",
        "lat": 23.2160,
        "lng": 75.7830,
        "mapQuery": "Kal Bhairav Temple Ujjain",
        "nearestRail": "Ujjain Junction",
        "nearestAirport": "Indore",
        "officialWebsite": "https://www.mptourism.com/",
    },
    {
        "slug": "iskcon-vrindavan",
        "name": "ISKCON Krishna Balaram Mandir, Vrindavan",
        "deity": "Krishna–Balaram (ISKCON)",
        "location": "Raman Reti, Vrindavan, Uttar Pradesh",
        "state": "Uttar Pradesh",
        "country": "India",
        "glyph": "इ",
        "famousFor": "ISKCON’s founding-era Vrindavan temple",
        "summary": "Krishna–Balaram Mandir — ISKCON’s iconic modern temple in Braj.",
        "mythology": "Established in Prabhupada’s lifetime, this temple anchors global ISKCON pilgrimage to Vrindavan with Western and Indian devotees sharing kirtan culture.",
        "lat": 27.5728,
        "lng": 77.6755,
        "mapQuery": "ISKCON Krishna Balaram Mandir Vrindavan",
        "nearestRail": "Mathura Junction",
        "nearestAirport": "Agra / Delhi",
        "officialWebsite": "https://iskconvrindavan.com/",
        "tags_extra": ["modern-temples"],
        "festivals": ["Janmashtami", "Gaura Purnima"],
    },
]


def attach_portal(detail: dict) -> dict:
    state = detail.get("state", "")
    portal = PORTALS.get(state)
    if not portal:
        return detail
    sources = list(detail.get("sources", []))
    line = f"{portal['portalName']}: {portal['portalUrl']}"
    if line not in sources:
        sources = [line] + sources
    for a in portal.get("also", []):
        extra = f"{a['name']}: {a['url']}"
        if extra not in sources:
            sources.append(extra)
    detail["sources"] = sources
    detail["statePortal"] = {
        "name": portal["portalName"],
        "url": portal["portalUrl"],
        "slug": portal["slug"],
    }
    if detail.get("officialWebsite") in ("https://tourism.gov.in/", "", None):
        detail["officialWebsite"] = portal["portalUrl"]
    return detail


def main() -> None:
    created = []
    for seed in NEW:
        slug = seed["slug"]
        path = TEMPLES / f"{slug}.json"
        tags_extra = seed.pop("tags_extra", [])
        if path.exists():
            detail = load_json(path)
            for k, v in seed.items():
                if k == "slug":
                    continue
                if k not in detail or not detail.get(k):
                    detail[k] = v
        else:
            detail = base_detail(seed)
            created.append(slug)
        tags = list(detail.get("tags", []))
        for t in tags_extra:
            if t not in tags:
                tags.append(t)
        detail["tags"] = tags
        detail = attach_portal(detail)
        dump_json(path, detail)

    # refresh portals on all
    for path in TEMPLES.glob("*.json"):
        detail = attach_portal(load_json(path))
        dump_json(path, detail)

    print(f"Expand temples: {len(NEW)} processed; new files: {len(created)}")
    for s in created:
        print(" +", s)
    subprocess.check_call([sys.executable, str(ROOT / "scripts" / "sync_groups.py")])


if __name__ == "__main__":
    main()
