#!/usr/bin/env python3
"""Append high-search story gaps (ritual-why / popular katha) to data/stories.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STORIES_PATH = ROOT / "data" / "stories.json"
ENGAGE_PATH = ROOT / "data" / "engagement.json"

NEW_STORIES = [
    {
        "slug": "ganesha-elephant-head",
        "title": "Why Ganesha has an elephant head",
        "titleHi": "गणेश जी का हाथी वाला मुख क्यों है",
        "readSeconds": 85,
        "deity": "ganesha",
        "tags": ["ritual-why", "first-timer", "family", "seo-gap"],
        "hook": "A mother’s guardian, a father’s trident, and the first creature facing north.",
        "hookHi": "माता का रक्षक, पिता का त्रिशूल, और उत्तरमुखी पहला प्राणी।",
        "whyRitual": "On Ganesh Chaturthi and before new beginnings, the elephant-headed form is remembered as restored life, wisdom, and the boon to be worshipped first.",
        "whyRitualHi": "गणेश चतुर्थी और हर शुभारंभ पर हाथी-मुख स्मृति है — पुनर्जीवन, बुद्धि, और प्रथम पूज्य का वर।",
        "storyEn": "When Parvati fashioned a boy from the unguents of her bath and set him to guard her door, he obeyed without knowing Shiva. The Lord, denied entry, struck in anger and severed the child’s head. Grief and fury shook the worlds. To restore the boy, tradition says Shiva’s attendants were sent for the head of the first creature found facing north — an elephant. Placed upon the body and breathed into life, the child became Ganesha: vast ears that hear every prayer, a trunk that clears the path, and a form that teaches that even broken beginnings can be made sacred again. Parvati’s condition — that he be worshipped before all gods — sealed his place at every doorway of auspicious work.",
        "storyHi": "पार्वती जी ने स्नान के उबटन से बालक गढ़ा और द्वार रक्षक बनाया। शिव जी आने पर बालक ने — माता की आज्ञा से — प्रवेश नहीं दिया। क्रोध में शिर कट गया; लोक व्याकुल हुए। पुनर्जीवन हेतु कहा जाता है — उत्तरमुखी प्रथम प्राणी का शिर लाओ; वह हाथी था। उसी शिर से बालक गणेश बने — विशाल कर्ण जो प्रार्थना सुनते, सूंड जो मार्ग साफ करती। पार्वती जी की शर्त — सब देवों से पहले इनकी पूजा — हर शुभ द्वार पर गणेश जी को बैठाती है।",
        "takeaway": "Before a new task, pause at Ganesha’s form — restore what anger broke, then begin.",
        "relatedDevotion": ["ganesha-aarti", "ganesha-chalisa", "ganesh-chaturthi-vrat-katha"],
        "relatedFestivals": ["ganesh-chaturthi"],
        "relatedTemples": ["siddhivinayak-mumbai", "moreshwar-morgaon"],
    },
    {
        "slug": "ganesha-prathama-pujya",
        "title": "Why Ganesha is worshipped first",
        "titleHi": "गणेश जी की पूजा सबसे पहले क्यों होती है",
        "readSeconds": 75,
        "deity": "ganesha",
        "tags": ["ritual-why", "first-timer", "family", "seo-gap"],
        "hook": "A race around the world — won by walking around parents.",
        "hookHi": "जगत की दौड़ — माता–पिता की परिक्रमा से जीती गई।",
        "whyRitual": "Every puja begins with Ganesha because tradition remembers him as Prathama Pujya — remover of obstacles at the start of sacred work.",
        "whyRitualHi": "हर पूजा गणेश जी से इसलिए शुरू होती है कि वे प्रथमा पूज्य हैं — कार्यारंभ के विघ्नहर्ता।",
        "storyEn": "The gods sought a leader of beginnings. Kartikeya raced his peacock around the earth; Ganesha, knowing he could not match that speed on his mouse, walked slowly around Shiva and Parvati. ‘You are my world,’ he said. Parents and gods declared him winner — not for distance travelled, but for understanding that the sacred centre is closer than the horizon. From that insight came the boon: invoke Ganesha first, so undertakings begin with humility rather than haste.",
        "storyHi": "आरंभ का अधिपति कौन हो — यह प्रश्न उठा। कार्तिकेय जी मोर पर पृथ्वी की परिक्रमा को दौड़े; गणेश जी मूषक पर जानते थे कि वेग नहीं जीतेंगे। उन्होंने धीरे शिव–पार्वती की परिक्रमा की — ‘आप ही मेरे जगत हैं।’ दूरी नहीं, भाव जीता। तभी से वर — पहले गणेश जी का आह्वान; जल्दबाजी नहीं, विनम्र आरंभ।",
        "takeaway": "Start one task today by naming what truly matters — then take the first step.",
        "relatedDevotion": ["ganesha-aarti", "ganesha-chalisa"],
        "relatedFestivals": ["ganesh-chaturthi"],
        "relatedTemples": ["siddhivinayak-mumbai", "moreshwar-morgaon"],
    },
    {
        "slug": "shiva-third-eye",
        "title": "Why Shiva has a third eye",
        "titleHi": "शिव जी का तीसरा नेत्र क्यों है",
        "readSeconds": 80,
        "deity": "shiva",
        "tags": ["ritual-why", "first-timer", "seo-gap"],
        "hook": "Two eyes see the world — the third burns illusion when the worlds forget.",
        "hookHi": "दो नेत्र जगत देखते — तीसरा तब जलाता जब मोह छा जाए।",
        "whyRitual": "Tripundra and meditation on Shiva’s gaze remember discernment — not rage for its own sake, but fire that ends falsehood.",
        "whyRitualHi": "त्रिपुंड और ध्यान शिव दृष्टि याद दिलाते हैं — क्रोध नहीं, मिथ्या का अंत करने वाली ज्योति।",
        "storyEn": "Puranic tellings say Shiva’s third eye opened when desire and distraction threatened cosmic balance — most famously when Kamadeva tried to disturb his tapasya, and the Lord’s gaze reduced the god of desire to ash. The eye is not merely anger; it is jnana-agni, the fire of seeing truly. Devotees mark three lines of ash as tripundra — reminders that creation, preservation, and dissolution are held in one awareness. To remember the third eye at home is to ask: what illusion am I feeding today?",
        "storyHi": "पुराण कहते हैं — जब काम और विक्षेप तप भंग करने आए, शिव जी का तृतीय नेत्र खुला; कामदेव भस्म हुए। यह नेत्र केवल रोष नहीं — ज्ञान-अग्नि है। भक्त त्रिपुंड भस्म लगाते हैं — सृष्टि–स्थिति–संहार एक चेतना में। घर पर तीसरे नेत्र का स्मरण पूछता है — आज कौन-सा मोह पाल रहा हूँ?",
        "takeaway": "Before reacting, open the ‘third eye’ of pause — see the desire beneath the anger.",
        "relatedDevotion": ["shiva-aarti", "shiva-chalisa", "lingashtakam"],
        "relatedFestivals": ["maha-shivaratri", "shravan-sawan"],
        "relatedTemples": ["kashi-vishwanath", "kedarnath"],
    },
    {
        "slug": "shiva-crescent-moon",
        "title": "Why Shiva wears the crescent moon",
        "titleHi": "शिव जी शीश पर चंद्रमा क्यों धारण करते हैं",
        "readSeconds": 70,
        "deity": "shiva",
        "tags": ["ritual-why", "first-timer", "seo-gap"],
        "hook": "Time’s measure rests in the ascetic’s hair — cool light on fierce stillness.",
        "hookHi": "काल की माप जटा में — उग्र शांति पर शीतल ज्योति।",
        "whyRitual": "Somwar and Sawan Mondays honour Shiva as Soma-wearer — the moon that cools the heat of tapasya and marks sacred time.",
        "whyRitualHi": "सोमवार और सावन सोम शिव को सोमधारी मानते हैं — तप की गर्मी पर चंद्र की शीतलता।",
        "storyEn": "One strand of telling says Chandra, cursed and waning, sought refuge at Shiva’s jata. The Lord placed the crescent there — neither fully dark nor fully bright — so time itself could rest against still awareness. The moon on Shiva’s head becomes a teaching: even what wanes can be held without being crushed. Householders remember this on Mondays with milk and bilva — offering coolness to the fierce.",
        "storyHi": "एक कथा कहती है — शाप से क्षीण चंद्र शिव जटा में शरण आए। भगवान ने अर्धचंद्र धारण किया — न पूर्ण अँधेरा न पूर्ण प्रकाश — ताकि काल भी स्थिर चेतना पर टिके। शिक्षा: जो घटता है उसे कुचलो नहीं, थामो। सोमवार दूध–बिल्व से भक्त वही शीतलता अर्पित करते हैं।",
        "takeaway": "On a Monday, offer one cool word where your speech usually burns.",
        "relatedDevotion": ["shiva-aarti", "sawan-somwar-vrat-katha"],
        "relatedFestivals": ["shravan-sawan", "maha-shivaratri"],
        "relatedTemples": ["somnath", "trimbakeshwar"],
    },
    {
        "slug": "shiva-trishul",
        "title": "Why Shiva holds the trishul",
        "titleHi": "शिव जी त्रिशूल क्यों धारण करते हैं",
        "readSeconds": 70,
        "deity": "shiva",
        "tags": ["ritual-why", "first-timer", "seo-gap"],
        "hook": "Three points — one grip: balance of the gunas in a single hand.",
        "hookHi": "तीन शूल — एक मुट्ठी: तीन गुणों का संतुलन।",
        "whyRitual": "Icons of Shiva with trishul remind devotees that creation, preservation, and dissolution — and sattva, rajas, tamas — are held together, not fought separately.",
        "whyRitualHi": "त्रिशूल वाली मूर्ति याद दिलाती है — सृष्टि–स्थिति–लय और सत–रज–तम एक साथ संभाले जाते हैं।",
        "storyEn": "Tellings differ on how the trishul came to Shiva — some say Vishwakarma forged it; others link it to Vishnu’s gift or the goddess’s power. What devotees keep is the meaning: three tips for the three gunas, three times, three worlds — mastered by one who is neither lost in creation nor terrified of ending. The staff is fierce so that fear may be cut; the grip is steady so that force does not become cruelty.",
        "storyHi": "कथाएँ भिन्न — कोई विश्वकर्मा का शिल्प कहती, कोई विष्णु या शक्ति का दान। भक्त अर्थ रखते हैं: तीन शूल तीन गुण, तीन काल, तीन लोक — जिन्हें वह संभालते हैं जो सृष्टि में खोए नहीं, अंत से डरे नहीं। त्रिशूल उग्र है ताकि भय कटे; मुट्ठी स्थिर ताकि बल क्रूर न बने।",
        "takeaway": "Name three pulls on your mind today — then hold them in one calm decision.",
        "relatedDevotion": ["shiva-aarti", "shiva-chalisa"],
        "relatedFestivals": ["maha-shivaratri"],
        "relatedTemples": ["kashi-vishwanath", "mahakaleshwar-ujjain"],
    },
    {
        "slug": "nandi-shiva-vahana",
        "title": "Why Nandi sits before Shiva",
        "titleHi": "नंदी शिव जी के आगे क्यों विराजते हैं",
        "readSeconds": 70,
        "deity": "shiva",
        "tags": ["ritual-why", "first-timer", "seo-gap"],
        "hook": "The bull who never turns away — patience facing the sanctum.",
        "hookHi": "जो मुँह नहीं मोड़ता — गर्भगृह की ओर धैर्य।",
        "whyRitual": "In Shiva temples, devotees whisper wishes to Nandi’s ear and look through to the linga — the vahana as bridge of attention.",
        "whyRitualHi": "शिव मंदिर में भक्त नंदी के कान में मनोकामना कहते और लिंग की ओर देखते — वाहन ध्यान का सेतु।",
        "storyEn": "Nandi is remembered as Shiva’s foremost attendant and vahana — steadfast, watchful, never turning his back on the Lord. Folk practice asks the bull to carry a whispered prayer inward. The teaching is simple: before you demand darshan, practise the loyalty of waiting. Strength without restlessness — that is why the bull faces the sanctum while the world turns behind him.",
        "storyHi": "नंदी शिव के प्रमुख गण और वाहन — अडिग, जागरूक, प्रभु से मुँह नहीं मोड़ते। लोक रीति कान में प्रार्थना कहती है। शिक्षा: दर्शन माँगने से पहले प्रतीक्षा की निष्ठा सीखो। बिना बेचैनी का बल — इसलिए नंदी गर्भगृह की ओर, संसार पीठ पीछे।",
        "takeaway": "Whisper one honest wish — then wait without refreshing the phone of the mind.",
        "relatedDevotion": ["shiva-aarti", "lingashtakam"],
        "relatedFestivals": ["maha-shivaratri", "shravan-sawan"],
        "relatedTemples": ["kashi-vishwanath", "somnath"],
    },
    {
        "slug": "venkateswara-kubera-loan",
        "title": "Why devotees offer at Tirupati — Kubera’s loan",
        "titleHi": "तिरुपति पर दान क्यों — कुबेर का ऋण",
        "readSeconds": 90,
        "deity": "vishnu",
        "tags": ["ritual-why", "first-timer", "seo-gap", "temple-story"],
        "hook": "A divine wedding, a treasury loan, and a Kali-yuga promise still being repaid.",
        "hookHi": "दिव्य विवाह, खजाने का ऋण, और कलियुग का वादा जो अभी चुकता है।",
        "whyRitual": "Hundi offerings at Tirumala are popularly remembered as helping repay Srinivasa’s loan from Kubera — devotion as participation in the Lord’s earthly stay.",
        "whyRitualHi": "तिरुमल हुंडी दान लोकस्मृति में श्रीनिवास के कुबेर-ऋण की अदायगी है — प्रभु के धरती-वास में भागीदारी।",
        "storyEn": "Sthala-purana tellings of Tirumala say Vishnu as Srinivasa descended to the seven hills for the age of Kali. To wed Padmavati with proper honour, he borrowed an immense sum from Kubera, promising repayment through the ages by the gifts of devotees. That is why the Tirumala hundi is not only charity — in living belief it is help toward a vow that spans Kali-yuga. Whether one reads it as theology or sacred story, the moral for householders is clear: give without pride, and remember wealth as trust, not trophy.",
        "storyHi": "तिरुमल स्थल-पुराण कहते हैं — कलियुग हेतु विष्णु श्रीनिवास रूप में सप्तगिरि आए। पद्मावती विवाह की मर्यादा हेतु कुबेर से विशाल ऋण लिया; वचन — युगों तक भक्तों के अर्पण से चुकाऊँगा। इसलिए हुंडी केवल दान नहीं — जीवंत विश्वास में उस वचन में सहयोग। गृहस्थ शिक्षा: अभिमान बिना दो; धन ट्रस्ट है, ट्रॉफी नहीं।",
        "takeaway": "If you give, give quietly — as repayment of grace, not purchase of favour.",
        "relatedDevotion": ["vishnu-aarti", "vishnu-chalisa", "satyanarayan-vrat-katha"],
        "relatedFestivals": ["akshaya-tritiya", "kartik-purnima"],
        "relatedTemples": ["tirumala-venkateswara", "srikalahasti"],
    },
    {
        "slug": "srinivasa-padmavati",
        "title": "Srinivasa and Padmavati — the Tirumala wedding",
        "titleHi": "श्रीनिवास और पद्मावती — तिरुमल विवाह",
        "readSeconds": 85,
        "deity": "vishnu",
        "tags": ["festival", "first-timer", "seo-gap", "temple-story"],
        "hook": "Lakshmi’s earthly birth, a hunter-prince’s love, and hills that became home.",
        "hookHi": "लक्ष्मी का धरती जन्म, राजकुमारी प्रेम, और पहाड़ जो घर बने।",
        "whyRitual": "Pilgrims traditionally visit Padmavati at Tiruchanur before Tirumala — honouring the consort before the Lord of the hills.",
        "whyRitualHi": "यात्री प्रायः पहले तिरुचनूर पद्मावती दर्शन करते — गिरिस्वामी से पहले शक्ति का सम्मान।",
        "storyEn": "After a heavenly quarrel in some tellings, Lakshmi left Vaikuntha and Vishnu searched the earth as Srinivasa. Padmavati, born to a royal line near the Venkata hills, met him in a forest of destiny. Their wedding at Narayanavanam became the hinge of Tirumala’s living faith — love that chooses to stay among humans. The hills hold the Lord; Tiruchanur holds the Goddess. Together they teach that pilgrimage is relationship, not only queue.",
        "storyHi": "कुछ कथाओं में लक्ष्मी वैकुंठ छोड़तीं; विष्णु श्रीनिवास रूप में पृथ्वी खोजते। पद्मावती — वेंकट गिरि के राजवंश में जन्मी — वन में मिलीं। नारायणवनम विवाह तिरुमल आस्था का केंद्र बना — प्रेम जो मनुष्यों के बीच ठहरता। पहाड़ प्रभु संभालते; तिरुचनूर देवी। तीर्थ संबंध है, केवल कतार नहीं।",
        "takeaway": "Before a big ask, honour the relationships that made your journey possible.",
        "relatedDevotion": ["lakshmi-aarti", "vishnu-aarti"],
        "relatedFestivals": ["diwali", "akshaya-tritiya"],
        "relatedTemples": ["tirumala-venkateswara"],
    },
    {
        "slug": "kartikeya-six-faces",
        "title": "Kartikeya — the six-faced commander",
        "titleHi": "कार्तिकेय — षण्मुख स्कंद",
        "readSeconds": 85,
        "deity": "shiva",
        "tags": ["ritual-why", "first-timer", "seo-gap", "south"],
        "hook": "Born of fire and river, raised by six mothers — the general of the gods.",
        "hookHi": "अग्नि और नदी से जन्म, छह माताओं का पालन — देवसेनापति।",
        "whyRitual": "Skanda Shashti and Murugan festivals honour Kartikeya’s victory over asuras — courage guided by many-sided wisdom.",
        "whyRitualHi": "स्कंद षष्ठी और मुरुगन उत्सव कार्तिकेय की असुर-विजय याद करते — बहुमुखी ज्ञान वाला साहस।",
        "storyEn": "When the asura Taraka threatened the gods, a commander was needed whom only Shiva’s spark could father. Sparks of Shiva’s energy, carried by Agni and cooled in Ganga, became six infants nurtured by the Krittikas — hence Kartikeya, Shanmukha of six faces. He grew into Skanda, general of the divine army, and defeated Taraka. Six faces mean seeing in all directions; the spear (vel) means one-pointed purpose. South Indian Murugan devotion and North Indian Kartik remembrance share this youth of war who is also a teacher of courage.",
        "storyHi": "जब तारकासुर ने देवों को पीड़ा दी, सेनापति चाहिए था — शिव तेज से जन्मा। अग्नि वाहक, गंगा शीतल, कृत्तिकाओं ने छह शिशु पाले — इसलिए कार्तिकेय, षण्मुख। वे स्कंद बने, देवसेना नायक, तारक वध। छह मुख — सब दिशा देखना; वेल — एक लक्ष्य। दक्षिण मुरुगन और उत्तर कार्तिक स्मृति एक ही युवा योद्धा–गुरु की हैं।",
        "takeaway": "Face one fear from six angles — then act with a single clean decision.",
        "relatedDevotion": ["shiva-aarti"],
        "relatedFestivals": ["maha-shivaratri"],
        "relatedTemples": ["sabarimala", "meenakshi-madurai"],
    },
    {
        "slug": "sati-daksha-yajna",
        "title": "Sati, Daksha’s yajna, and the birth of Shakti Peethas",
        "titleHi": "सती, दक्ष यज्ञ और शक्ति पीठों का उदय",
        "readSeconds": 95,
        "deity": "devi",
        "tags": ["ritual-why", "first-timer", "seo-gap"],
        "hook": "An insult at a sacrifice, a goddess’s fire, and fragments that sanctified the earth.",
        "hookHi": "यज्ञ में अपमान, देवी की ज्वाला, और अंश जिन्होंने धरती को तीर्थ बनाया।",
        "whyRitual": "Shakti Peetha pilgrimage remembers where Sati’s body fell — the Goddess as geography, grief transformed into seats of power.",
        "whyRitualHi": "शक्ति पीठ यात्रा सती देह-पतन स्थल याद करती — शोक से जन्मी शक्ति की भूगोल।",
        "storyEn": "Daksha held a great yajna and slighted Shiva. Sati, Daksha’s daughter and Shiva’s consort, could not bear the insult to her Lord; in anguish she entered the yogic fire. Shiva’s grief became the tandava that threatened worlds. Vishnu’s discus, in the telling, divided Sati’s form; wherever a portion fell, a peetha of the Goddess arose. That map of peethas is why Devi temples across the subcontinent feel like one mother’s body remembered in many places. The story warns against pride in ritual that forgets reverence.",
        "storyHi": "दक्ष ने यज्ञ किया और शिव का अपमान। पुत्री सती — शिवा की पत्नी — अपमान न सह सकीं; योगाग्नि में समा गईं। शिव का शोक तांडव बना। कथा में विष्णु चक्र से सती देह खंडित हुई; जहाँ अंश गिरा, शक्ति पीठ जन्मा। इसलिए उपमहाद्वीप के देवी मंदिर एक माँ की देह-स्मृति लगते। शिक्षा: रीति का अहंकार श्रद्धा भूल जाए तो यज्ञ भी हिंसा बनता।",
        "takeaway": "Before you host a celebration, check whom your pride might exclude.",
        "relatedDevotion": ["devi-aarti", "durga-chalisa", "navaratri-vrat-katha"],
        "relatedFestivals": ["navaratri", "maha-shivaratri"],
        "relatedTemples": ["kamakhya", "vaishno-devi", "vishalakshi-kashi"],
    },
    {
        "slug": "ayyappa-manikandan",
        "title": "Ayyappa — the child of Hari and Hara",
        "titleHi": "अय्यप्पा — हरि–हर पुत्र मणिकंदन",
        "readSeconds": 90,
        "deity": "ayyappa",
        "tags": ["ritual-why", "first-timer", "seo-gap", "south"],
        "hook": "Vishnu as Mohini, Shiva’s grace, and a prince who chose the forest of vows.",
        "hookHi": "मोहिनी रूप विष्णु, शिव कृपा, और राजकुमार जिसने व्रत-वन चुना।",
        "whyRitual": "Sabarimala Mandala season remembers Manikandan’s tapasya — discipline, irumudi, and equality of devotees in black.",
        "whyRitualHi": "सबरीमला मण्डल मणिकंदन की तप याद करता — अनुशासन, इरुमुडि, और काले वस्त्र में समता।",
        "storyEn": "To destroy the asura Mahishi, a child was needed of both Hari and Hara. Vishnu as Mohini and Shiva’s union, in Kerala telling, gave Manikandan to a childless king. The boy’s miracles and compassion revealed his divinity; he chose the hill of Sabari for eternal tapasya rather than a throne. Pilgrims still climb with irumudi, fasting and singing ‘Swamiye Saranam Ayyappa’ — not tourism, but a vow of shared austerity.",
        "storyHi": "महिषी असुर वध हेतु हरि–हर पुत्र चाहिए था। केरल कथा में मोहिनी–शिव संयोग से मणिकंदन निःसंतान राजा को मिले। चमत्कार और करुणा से दिव्यता प्रकट हुई; सिंहासन छोड़ सबरी गिरि तप चुना। आज भी इरुमुडि, व्रत, ‘स्वामिये शरणं अय्यप्पा’ — पर्यटन नहीं, साझा तप का वचन।",
        "takeaway": "Keep one small vow this week that costs comfort but costs no one else.",
        "relatedDevotion": ["ayyappa-aarti", "ayyappa-chalisa", "ayyappa-mandala-vrat-katha"],
        "relatedFestivals": ["makar-sankranti"],
        "relatedTemples": ["sabarimala"],
    },
    {
        "slug": "jagannath-neem-murti",
        "title": "Why Jagannath’s murti is of wood",
        "titleHi": "जगन्नाथ जी की मूर्ति काठ की क्यों है",
        "readSeconds": 85,
        "deity": "krishna",
        "tags": ["ritual-why", "first-timer", "seo-gap", "temple-story"],
        "hook": "An unfinished carving, a king’s dream, and arms that never close the devotee out.",
        "hookHi": "अधूरी तक्षणा, राजा का स्वप्न, और भुजाएँ जो भक्त को बाहर नहीं करतीं।",
        "whyRitual": "Rath Yatra and Nabakalebara renew the wooden forms — impermanence itself made sacred in Puri.",
        "whyRitualHi": "रथ यात्रा और नवकेलेबर काष्ठ रूप नवाते — अनित्यता को ही पुरी में पवित्र माना।",
        "storyEn": "Odia tradition tells of King Indradyumna seeking a form of the Lord. A divine carpenter agreed to carve in secret; when the impatient king opened the door early, the work stopped — unfinished arms, large eyes, a presence more intimate than polished stone. Every so often the neem forms are renewed in Nabakalebara. Jagannath, Balabhadra, and Subhadra ride chariots so the street becomes the sanctum. The incomplete arms are not a flaw; they are an invitation — the Lord still being carved by devotion.",
        "storyHi": "ओडिया कथा — राजा इंद्रद्युम्न प्रभु रूप चाहते। दिव्य शिल्पी ने गुप्त तक्षणा मानी; अधीर राजा ने द्वार जल्दी खोला — कार्य रुका: अधूरी भुजा, विशाल नेत्र, पत्थर से अधिक आत्मीय उपस्थिति। समय–समय नवकेलेबर में नीम रूप नये होते। जगन्नाथ–बलभद्र–सुभद्रा रथ पर — गली ही गर्भगृह। अधूरी भुजा दोष नहीं — निमंत्रण: भक्ति अभी तक्षणा जारी रखती।",
        "takeaway": "Leave one work imperfect on purpose — and share it, as Puri shares its Lord with the street.",
        "relatedDevotion": ["krishna-aarti", "vishnu-aarti"],
        "relatedFestivals": ["rath-yatra"],
        "relatedTemples": ["jagannath-puri"],
    },
    {
        "slug": "meenakshi-sundareswarar",
        "title": "Meenakshi and Sundareswarar — Madurai’s divine wedding",
        "titleHi": "मीनाक्षी–सुंदरेश्वर — मदुरै दिव्य विवाह",
        "readSeconds": 80,
        "deity": "devi",
        "tags": ["festival", "first-timer", "seo-gap", "temple-story", "south"],
        "hook": "A fish-eyed princess who ruled, then wed Shiva — and a city became their courtyard.",
        "hookHi": "मत्स्याक्षी राजकुमारी जो राज्य करतीं, फिर शिव संग ब्याहीं — नगर आंगन बना।",
        "whyRitual": "Chithirai festival reenacts the wedding — Madurai’s identity as the living home of the Goddess and Shiva.",
        "whyRitualHi": "चित्रै उत्सव विवाह का पुनराभिनय — मदुरै देवी–शिव का जीवंत घर।",
        "storyEn": "Meenakshi, the fish-eyed goddess-princess of Pandya lore, conquered directions until she met Sundareswarar — Shiva as the beautiful lord — and the warrior became the bride. Their wedding is not a side story; it is Madurai’s heartbeat, carved into gopurams and danced in Chithirai streets. The temple teaches that Shakti and Shiva are not rivals of power but partners of a city’s sacred life.",
        "storyHi": "मीनाक्षी — पांड्य कथा की मत्स्याक्षी राजकुमारी — दिशाएँ जीततीं जब तक सुंदरेश्वर मिले — शिव सुंदर रूप में — और योद्धा दुल्हन बनीं। विवाह उपकथा नहीं; मदुरै की धड़कन है, गोपुरम में खुदी, चित्रै गलियों में नाची। मंदिर सिखाता — शक्ति और शिव सत्ता के प्रतिद्वंद्वी नहीं, नगर की पवित्र जीवन-साझी।",
        "takeaway": "Honour partnership in your home the way Madurai honours Meenakshi’s wedding — with public joy, not private scorekeeping.",
        "relatedDevotion": ["devi-aarti", "shiva-aarti"],
        "relatedFestivals": ["navaratri"],
        "relatedTemples": ["meenakshi-madurai"],
    },
    {
        "slug": "santoshi-mata-friday",
        "title": "Santoshi Mata — the Mother of contentment",
        "titleHi": "संतोषी माता — संतोष की माँ",
        "readSeconds": 90,
        "deity": "devi",
        "tags": ["ritual-why", "festival", "family", "seo-gap"],
        "hook": "Sixteen Fridays, gur and chana, and a vow against sourness of tongue and heart.",
        "hookHi": "सोलह शुक्रवार, गुड़–चना, और खट्टापन के विरुद्ध वचन — जीभ और मन का।",
        "whyRitual": "Friday Santoshi Mata vrat with jaggery–chickpea bhog seeks household peace through santosh — contentment — not display.",
        "whyRitualHi": "शुक्रवार संतोषी व्रत गुड़–चना से गृह शांति माँगता — प्रदर्शन नहीं, संतोष।",
        "storyEn": "In popular vow tradition, Santoshi Mata — remembered as daughter of Ganesha — blesses those who keep sixteen Fridays with simple bhog of gur and chana and avoid all that is sour. The katha of a mistreated daughter-in-law whose fortune returns through patient fasting teaches that jealousy can sour a completed vow, and that contentment is itself the goddess’s gift. TirthaYatra retells the theme for home learning: keep the rule of kindness sharper than the rule of food.",
        "storyHi": "लोकव्रत में संतोषी माता — गणेश पुत्री के रूप में स्मृत — सोलह शुक्रवार, गुड़–चना भोग और खट्टे के त्याग से प्रसन्न होतीं। बहू की कथा जिसका भाग्य धैर्य से लौटा, सिखाती — ईर्ष्या पूरे व्रत को खट्टा कर सकती; संतोष ही वर है। घर की शिक्षा: भोजन नियम से बढ़कर दया नियम रखो।",
        "takeaway": "This Friday, skip one sour remark — offer sweetness of speech with your meal.",
        "relatedDevotion": ["santoshi-chalisa", "devi-aarti"],
        "relatedFestivals": ["navaratri"],
        "relatedTemples": ["siddhivinayak-mumbai", "mansa-devi-panchkula"],
    },
    {
        "slug": "shani-dev-justice",
        "title": "Shani Dev — why Saturday asks for justice",
        "titleHi": "शनि देव — शनिवार न्याय क्यों माँगता है",
        "readSeconds": 80,
        "deity": "shiva",
        "tags": ["ritual-why", "first-timer", "seo-gap"],
        "hook": "Slow planet, strict mirror — karma that arrives without hurry.",
        "hookHi": "धीर ग्रह, कठोर दर्पण — कर्म जो जल्दी नहीं, चूकता नहीं।",
        "whyRitual": "Saturday oil, sesame, and Shani Chalisa seek patience under consequence — not panic bargaining.",
        "whyRitualHi": "शनिवार तेल–तिल और शनि चालीसा धैर्य माँगते — भय से सौदा नहीं।",
        "storyEn": "Shani is remembered as the lord of slow, exacting justice — the planet that matures what we plant. Folk fear sometimes turns into superstition; wiser devotion treats Shani as a teacher of accountability. Offering oil and black sesame, reading Shani Chalisa, and correcting one’s own delay or deceit matters more than blaming a day of the week. Where open-air shrines like Shani Shingnapur stand without doors, the story people tell is trust: live so honestly that locks become less necessary.",
        "storyHi": "शनि धीमे–सटीक न्याय के स्वामी — जो बोया पकता है। लोकभय कभी अंधविश्वास बनता; सयानी भक्ति शनि को जवाबदेही का गुरु मानती। तेल–तिल, शनि चालीसा, और अपना विलंब/छल सुधारना — दिन को दोष देने से बड़ा। जहाँ शनि शिंगणापुर जैसे खुले स्थान द्वार रहित कहे जाते, कथा विश्वास की है: इतने ईमान से जियो कि ताले कम पड़ें।",
        "takeaway": "Repair one delayed duty on Saturday — that is better oil than fear.",
        "relatedDevotion": ["shani-chalisa", "hanuman-chalisa"],
        "relatedFestivals": ["diwali"],
        "relatedTemples": ["trimbakeshwar", "mahakaleshwar-ujjain"],
    },
    {
        "slug": "hanuman-lanka-agni",
        "title": "Why Hanuman’s tail burned Lanka",
        "titleHi": "हनुमान जी की पूँछ ने लंका क्यों जलाई",
        "readSeconds": 80,
        "deity": "hanuman",
        "tags": ["ritual-why", "first-timer", "family", "seo-gap"],
        "hook": "Bound as a messenger, set alight as a joke — the fire returned as justice.",
        "hookHi": "दूत बँधे, हँसी में जलाए — अग्नि न्याय बनकर लौटी।",
        "whyRitual": "Hanuman Jayanti and Tuesday/Saturday recitation remember strength used for Rama’s mission — not for ego display.",
        "whyRitualHi": "हनुमान जयंती और मंगल/शनि पाठ राम-कार्य का बल याद करते — अहंकार प्रदर्शन नहीं।",
        "storyEn": "In Lanka, Hanuman was captured after finding Sita. Ravana’s court mocked the messenger and wrapped his tail in cloth and oil, intending humiliation by fire. Hanuman grew; the burning tail became a torch that set proud roofs alight, then he leapt to the sea to cool. The episode is not celebration of destruction — it is warning: cruelty toward a humble envoy returns upon the cruel. Bajrangbali’s strength serves dharma’s message first.",
        "storyHi": "सीता खोजकर हनुमान लंका में पकड़े गए। रावण सभा ने दूत का अपमान कर पूँछ कपड़े–तेल से जलाई। हनुमान बढ़े; जलती पूँछ मशाल बनी, अहंकारी छतें जलीं; फिर समुद्र में शीतल हुए। यह विनाश उत्सव नहीं — चेतावनी: विनम्र दूत पर क्रूरता क्रूर पर लौटती। बजरंगबली का बल पहले धर्म-संदेश का सेवक।",
        "takeaway": "Defend the messenger in your life — do not mock the one who brings hard truth.",
        "relatedDevotion": ["hanuman-aarti", "hanuman-chalisa", "hanuman-jayanti-vrat-katha"],
        "relatedFestivals": ["hanuman-jayanti"],
        "relatedTemples": ["salasar-balaji", "sankat-mochan-varanasi"],
    },
    {
        "slug": "tulsi-vivah-vishnu",
        "title": "Tulsi Vivah — why basil marries Vishnu",
        "titleHi": "तुलसी विवाह — तुलसी विष्णु से क्यों ब्याही जाती हैं",
        "readSeconds": 80,
        "deity": "vishnu",
        "tags": ["ritual-why", "festival", "family", "seo-gap"],
        "hook": "A plant in the courtyard becomes a bride — Kartik’s vow of domestic sanctity.",
        "hookHi": "आंगन का पौधा दुल्हन बनता — कार्तिक का गृह पवित्रता व्रत।",
        "whyRitual": "Tulsi Vivah in Kartik marks the end of monsoon austerity and the wedding of Tulsi with Vishnu / Shaligram — opening the marriage season in many homes.",
        "whyRitualHi": "कार्तिक तुलसी विवाह वर्षा-तप का अंत और तुलसी–विष्णु/शालिग्राम ब्याह — कई घरों में विवाह काल का आरंभ।",
        "storyEn": "Puranic and folk strands remember Tulsi as a devoted being whose earthly form is the basil plant sacred to Vishnu. In Kartik, households celebrate her symbolic wedding to the Lord (often as Shaligram). The rite sanctifies the courtyard garden and teaches that daily care of a living plant can be devotion — watering as worship, leaf as offering. After Tulsi Vivah, many communities consider the wedding season open.",
        "storyHi": "पुराण–लोक में तुलसी भक्त सत्ता हैं जिनका धरती रूप विष्णु-प्रिय तुलसी है। कार्तिक में घर उनका प्रतीकात्मक विवाह प्रभु (अक्सर शालिग्राम) से मनाते। रीति आंगन को पवित्र करती — पौधे की रोज सेवा भी भक्ति: जल अर्पण, पत्र भोग। तुलसी विवाह के बाद कई समाजों में विवाह काल खुलता।",
        "takeaway": "Water one living plant as if it were a guest of God — then keep the habit.",
        "relatedDevotion": ["vishnu-aarti", "lakshmi-aarti"],
        "relatedFestivals": ["kartik-purnima", "diwali"],
        "relatedTemples": ["tirumala-venkateswara", "dwarka"],
    },
    {
        "slug": "annapurna-feeds-shiva",
        "title": "Annapurna — when Shiva begged for food",
        "titleHi": "अन्नपूर्णा — जब शिव ने अन्न माँगा",
        "readSeconds": 75,
        "deity": "devi",
        "tags": ["ritual-why", "first-timer", "seo-gap"],
        "hook": "The Lord of renunciation learns hunger — and the Goddess becomes the kitchen of the world.",
        "hookHi": "वैराग्य के स्वामी को भूख सिखाई — देवी जगत की रसोई बनीं।",
        "whyRitual": "Annapurna worship and food-daan remember that nourishment is sacred — do not waste grain; do not shame hunger.",
        "whyRitualHi": "अन्नपूर्णा पूजा और अन्नदान याद दिलाते — अन्न पवित्र; बर्बाद मत करो, भूख का अपमान मत करो।",
        "storyEn": "In a famous Kashi telling, Shiva once declared the world may run on knowledge alone. The Goddess withdrew food; existence starved. Shiva himself came as a mendicant before Annapurna, who served him rice with her own hands. The teaching restored balance: wisdom without nourishment is cruelty; kitchens are temples. Every meal offered without arrogance is a small Annapurna rite.",
        "storyHi": "काशी कथा — शिव ने कहा जगत केवल ज्ञान से चले। देवी ने अन्न रोक दिया; सृष्टि भूखी। शिव भिक्षुक बन अन्नपूर्णा के आगे आए; उन्होंने स्वयं अन्न परोसा। शिक्षा: बिना पोषण का ज्ञान क्रूर; रसोई मंदिर। बिना अहंकार का हर भोजन छोटा अन्नपूर्णा व्रत।",
        "takeaway": "Do not waste today’s rice — and share one meal without commentary.",
        "relatedDevotion": ["devi-aarti", "annapurna"],
        "relatedFestivals": ["diwali", "navaratri"],
        "relatedTemples": ["kashi-vishwanath", "vishalakshi-kashi"],
    },
    {
        "slug": "jatayu-rama",
        "title": "Jatayu — the bird who fought for Sita",
        "titleHi": "जटायु — सीता हेतु लड़ने वाला पक्षी",
        "readSeconds": 75,
        "deity": "rama",
        "tags": ["family", "first-timer", "seo-gap"],
        "hook": "Old wings against a flying chariot — courage that outlived the body.",
        "hookHi": "उड़ते रथ के सामने वृद्ध पंख — काया से बड़ी हिम्मत।",
        "whyRitual": "Ramayana trails honour Jatayu’s sacrifice — friendship and duty beyond age and species.",
        "whyRitualHi": "रामायण पथ जटायु बलिदान याद करते — आयु और योनि से परे मित्रधर्म।",
        "storyEn": "When Ravana carried Sita away, the aged vulture-king Jatayu rose to fight. He could not win; he could witness and wound and tell. Falling, he held life until Rama arrived, spoke the truth of the abduction, then left the body. Rama performed last rites as for a father. The story is taught to children so bravery is not confused with victory — sometimes the brave only manage to speak before they fall.",
        "storyHi": "जब रावण सीता हर ले गया, वृद्ध गृध्रराज जटायु लड़े। जीत नहीं सके; साक्षी बने, घायल किया, कहा। गिरकर प्राण रोके जब तक राम आए, हरण सत्य कहा, तब देह छोड़ी। राम ने पिता-सा संस्कार किया। बच्चों को सिखाएँ — शौर्य हमेशा विजय नहीं; कभी वीर केवल गिरने से पहले बोल पाते।",
        "takeaway": "Speak one true word for someone who cannot — that is Jatayu’s share.",
        "relatedDevotion": ["rama-aarti", "rama-chalisa"],
        "relatedFestivals": ["ram-navami", "dussehra"],
        "relatedTemples": ["ayodhya-ram-mandir", "rameswaram"],
    },
    {
        "slug": "vitthal-pandharpur",
        "title": "Vitthal of Pandharpur — the Lord on the brick",
        "titleHi": "पंढरपुर के विठ्ठल — ईंट पर खड़े प्रभु",
        "readSeconds": 80,
        "deity": "krishna",
        "tags": ["ritual-why", "first-timer", "seo-gap", "temple-story"],
        "hook": "A devotee’s delayed duty, a waiting God, and abhangs that still walk the road.",
        "hookHi": "भक्त का रुका कर्तव्य, प्रतीक्षारत भगवान, और अभंग जो अभी पंढरी पथ चलते।",
        "whyRitual": "Ashadhi and Kartiki Wari to Pandharpur remember Vithoba — devotion that stands where the devotee’s duty stood.",
        "whyRitualHi": "आषाढ़ी–कार्तिकी वारी विठोबा याद करती — भक्ति वहाँ ठहरती जहाँ भक्त का धर्म ठहरा।",
        "storyEn": "Warkari telling remembers Pundalik serving his parents when Krishna arrived. The devotee offered the Lord a brick to stand upon until service was done — and Vitthal remained, hands on hips, eternally patient on that brick at Pandharpur. Saints’ abhangs turned the pilgrimage into song. The image teaches: God can wait while you finish honouring the living; do not use bhakti to escape duty.",
        "storyHi": "वारकरी कथा — पुंडलिक माता–पिता सेवा में थे जब कृष्ण आए। भक्त ने प्रभु को ईंट दी — सेवा पूर्ण होने तक खड़े रहो — विठ्ठल पंढरपुर में कमर पर हाथ, उस ईंट पर सदा। संतों के अभंग ने यात्रा को गीत बना दिया। शिक्षा: जीवित के सम्मान में भगवान प्रतीक्षा कर सकते; भक्ति से कर्तव्य न भागें।",
        "takeaway": "Finish one duty to parents or elders before your next ‘spiritual’ scroll.",
        "relatedDevotion": ["krishna-aarti", "vishnu-aarti"],
        "relatedFestivals": ["kartik-purnima"],
        "relatedTemples": ["pandharpur-vitthal"],
    },
    {
        "slug": "parashurama-avatar",
        "title": "Parashurama — the axe that defended dharma",
        "titleHi": "परशुराम — धर्म रक्षक परशु",
        "readSeconds": 85,
        "deity": "vishnu",
        "tags": ["ritual-why", "first-timer", "seo-gap"],
        "hook": "Brahmin with an axe, warrior with a vow — the avatar who would not ignore tyranny.",
        "hookHi": "परशु वाले ब्राह्मण, व्रत वाले योद्धा — अवतार जिसने अत्याचार अनदेखा नहीं किया।",
        "whyRitual": "Parashurama Jayanti and coastal Konkan–Kerala lore remember the sixth avatar — fierce correction of power without compassion.",
        "whyRitualHi": "परशुराम जयंती और कोंकण–केरल स्मृति छठा अवतार — बिना करुणा की शक्ति का कठोर सुधार।",
        "storyEn": "Vishnu as Parashurama took birth to confront kshatriya arrogance that crushed the vulnerable. The axe (parashu) became his sign; the telling is stern — cycles of revenge that later meet Rama and learn limits. Householders should not romanticise violence; they should hear the warning: skill without restraint becomes oppression, and even an avatar’s fury must eventually bow to a fuller dharma.",
        "storyHi": "विष्णु परशुराम रूप में जन्मे — क्षत्रिय अहंकार जो दुर्बल कुचलता, उसका सामना। परशु चिह्न बना; कथा कठोर — प्रतिशोध चक्र जो आगे राम से मिल सीमा सीखता। गृहस्थ हिंसा महिमा न करें; चेतावनी सुनें: संयमहीन कौशल उत्पीड़न बनता, अवतार का रोष भी पूर्ण धर्म के आगे झुकता।",
        "takeaway": "Use one skill you have to protect someone weaker — then stop when justice is enough.",
        "relatedDevotion": ["vishnu-aarti", "rama-aarti"],
        "relatedFestivals": ["akshaya-tritiya"],
        "relatedTemples": ["trimbakeshwar", "rameswaram"],
    },
]


def main() -> None:
    data = json.loads(STORIES_PATH.read_text(encoding="utf-8"))
    existing = {s["slug"] for s in data["stories"]}
    added = []
    for story in NEW_STORIES:
        if story["slug"] in existing:
            continue
        # Drop relatedDevotion entries that may not exist yet
        if story["slug"] == "annapurna-feeds-shiva":
            story["relatedDevotion"] = ["devi-aarti", "lakshmi-aarti"]
        if story["slug"] == "kartikeya-six-faces":
            story["relatedTemples"] = ["sabarimala", "meenakshi-madurai"]
        data["stories"].append(story)
        added.append(story["slug"])
        existing.add(story["slug"])

    STORIES_PATH.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Added {len(added)} stories: {', '.join(added) or '(none — already present)'}")

    engage = json.loads(ENGAGE_PATH.read_text(encoding="utf-8"))
    rot = engage.setdefault("dailyRotation", {}).setdefault("story", [])
    for slug in added:
        if slug not in rot:
            rot.append(slug)
    ENGAGE_PATH.write_text(
        json.dumps(engage, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"dailyRotation stories now: {len(rot)}")


if __name__ == "__main__":
    main()
